services:   
  db:
    image: mariadb:10.5
    
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cricket
        
  webapp:
    image: cricket
 
    depends_on:
        - db
        
    ports:
        - 8000:8080    
 
       
        

    
      